### ISSUE TITLE
Monorepo 3rd party imports

### ISSUE THREAD

**Issue by KostiantynPopovych** [sdorra/content-collections#124]
Hey, first of all, thanks for a great tool!

I'm trying to integrate content-collections into my Next.js app, but the critical piece is that I have a monorepo with separate apps and packages. I have all of my mdx-related methods and plugins in a package, and I'm trying to import them to the Next app. When the execution of the content-collections script starts, it grabs all the imports from the `content-collections.ts` and puts them in the `content-collections-config.mjs`.

So far so good, my monorepo plugins and packages are present in the generated config file, but there are also their imports. Those imports are imports of 3rd party dependencies such as `remark`, and they can't be resolved in the execution time because they are not installed in the app itself. As I'm trying to separate the dependencies and not include unnecessary dependencies in my apps, 

I would like to ask for a suggestion for a possible solution for my case. I tried to build my lib so that all of the dependencies would be in the built files, but I'm facing an error in this case: `Dynamic require of "[node built-in module]" is not supported.`

Thanks in advance!

**Comment by sdorra** [comment]
Do you have a repository where I can reproduce the issue? I'm curious because most of the time, libraries such as `remark` are not required at runtime. If you transform your content to MDX at build time (as described [here](https://www.content-collections.dev/docs/content/mdx)), you do not need them at runtime.

**Comment by kostiantynatmodelyst** [comment]
I could prepare the repo, the current is a private unfortunately. Sorry if it was unclear, but the issue is with a build process. I tried both approaches utilizing yours plugin for next.js apps and a pure cli way to build my files.

When I run `content-collections build` the `content-collections-config.mjs` would have the following content:

```
// ../../packages/blog/src/plugins/index.ts
import remarkGfm from "remark-gfm";
```

And right after the file is created the command will throw an error that `remark-gfm` cannot be resolved. This dependency is installed in the `/packages/blog` package but not in the next.js app one.

**Comment by KostiantynPopovych** [comment]
I could prepare the repo, the current is a private unfortunately. Sorry if it was unclear, but the issue is with a build process. I tried both approaches utilizing yours plugin for next.js apps and a pure cli way to build my files.

When I run content-collections build the content-collections-config.mjs would have the following content:

// ../../packages/blog/src/plugins/index.ts
import remarkGfm from "remark-gfm";
And right after the file is created the command will throw an error that remark-gfm cannot be resolved. This dependency is installed in the /packages/blog package but not in the next.js app one.

**Comment by sdorra** [comment]
@KostiantynPopovych i was able to fix the typescript issues as well. `defineConfig` has spit out the following error:

```
The inferred type of 'default' cannot be named without a reference to '.pnpm/zod@3.23.8/node_modules/zod'. This is likely not portable. A type annotation is necessary
```

The issue can be fixed by setting `declaration` and `declarationMap` to `false`, which is only required for building libraries and is not useful for a next app. However i will check if i get content collections to work with declaration enabled.

**Comment by KostiantynPopovych** [comment]
Hey, @sdorra, thank you so much for your help! The solution you created works as expected for this case, and the issue might be closed.

However, I chose the Turbopack for this example to save time, which was my mistake. My original issue is in the TypeScript NX monorepo. It is a package-based monorepo with `commonjs` packages. The `content-collections` config file in the `web` app imports helpers/plugins from the `packages/blog/mdx` package by utilizing `tsconfig` paths for imports.

I created [another repo](https://github.com/KostiantynPopovych/content-collections-nx), the more accurate example with NX and TypeScript, where I tried to solve my issue by building the package and then importing everything from the `dist` folder. This attempts can be found on the `main` branch, and there, you will see the following error - `Error('Dynamic require of "' + x + '" is not supported')`—if you run the `nx dev web` command. The actual representation of a state of the original repo can be found on the [issue](https://github.com/KostiantynPopovych/content-collections-nx/tree/issue) branch.

For now, I will add all the necessary `devDepsendencies` to the web app and leave it be; I just lack time. And sorry for wasting your time on an irrelevant example!

**Comment by sdorra** [comment]
I'm not sure if this can work at all. I think this will cause trouble at least with pnpm. If you use the direct path (or an ts alias) to the package instead of relying on the package mechanism, content-collection will not be able to find the dependencies. I don't know if nx does some magic here. I don't have any experience with nx. I've tried to get your example repo work, but i don't know how to start. Can you give me some advice?

**Comment by sdorra** [comment]
@KostiantynPopovych I've looked in the documentation of nx and it seams to work fine with pnpm workspace packages. Can you just use a workspace dependency instead of the import with a type alias?

**Comment by KostiantynPopovych** [comment]
@sdorra Yeah, after some rethinking, I see that this should be done through installing all the necessary dev deps. Thanks a lot for helping me to investigate my trouble! The solution is found, and I am going to close this one.
