### ISSUE TITLE
Access documents of the current collection in `transform`

### ISSUE THREAD

**Issue by wottpal** [sdorra/content-collections#268]
Hey @sdorra, I would really appreciate if you could find a way to make this possible. Referring to https://github.com/sdorra/content-collections/issues/245.

My current workaround (probably interesting for you @Kuzry, too) is defining a dummy/helper collection first (with only very few schema attributes that all pages share like `slug` or `title`). And then I can iterate over those via `context.documents(helpers).map(…)` as usual.

Though, for performance & DRY reasons I would highly appreciate being able to access all pages in the transform function w/o that.

My suggestion: As I understand it's impossible to make them accessible post-transform, I would suggest having some kind of pre-transform document collections of the current collection being accessible during `transform` (hope that's understandable).

There are just so many use cases this would enable:

* Very helpful in multilingual setups where I want to determine the internationalized version of the current page.
* If I have some kind of embeddings and want to pre-compute "related pages".
* …

**Comment by sdorra** [comment]
I believe that it is already possible to access the documents of the collection in the transform function:

https://github.com/sdorra/content-collections/blob/8f0de86ace2b92ff8afa46b49d75821997c69944/packages/core/src/transformer.ts#L134

It is probably just a type problem.

https://github.com/sdorra/content-collections/blob/8f0de86ace2b92ff8afa46b49d75821997c69944/packages/core/src/config.ts#L50

At first glance it looks right. I'm on vacation for a week now, but I'll take a look at it when I get back.

**Comment by wottpal** [comment]
Wow this indeed seems to work, though I tried this before. 🤔 Amazing! 

Now I only need some kind of equivalent for the `GetTypeByName` generic to get the "pre-transform" type of a collection document.

**Comment by sdorra** [comment]
Okay, I've looked into it, and I believe it is not possible to get the types right for the documents function of the Context. This is because the function requires the collection as input, and it uses the type of the collection to determine the type of the resulting documents. However, the type of the collection is based on the result of the transform function. Therefore, we cannot use the type in a function that is required to determine the type. Does this make sense?

We could introduce a new API to retrieve the documents of the current collection. The context already includes a [collection](https://github.com/sdorra/content-collections/blob/8f0de86ace2b92ff8afa46b49d75821997c69944/packages/core/src/config.ts#L54-L56). We could add a `documents` function without any parameters. An example usage could look like this:

```ts
import { defineCollection, defineConfig } from "@content-collections/core";

const posts = defineCollection({
  name: "posts",
  directory: "sources/posts",
  include: "*.md",
  schema: (z) => ({
    title: z.string(),
    description: z.string(),
  }),
  transform: async (post, { collection }) => {
    const docs = await collection.documents()
    const idx = docs.indexOf(post);
    const prev = docs[idx - 1];
    const next = docs[idx + 1];

    return {
      ...post,
      prev,
      next
    }
  }
});

export default defineConfig({
  collections: [posts],
});
```

But I'm not sure about the naming. It's clear that the `ctx.documents` function is for retrieving documents from other collections, while `ctx.collections.documents` is for documents from the current collection?

**Comment by sdorra** [comment]
@wottpal, could you please check if the functionality of #290 meets your requirements?

To install the preview packages, add the package you need as described in this comment:

https://github.com/sdorra/content-collections/pull/290#issuecomment-2325255322

The documentation for the new feature can be found here:

https://content-collections-otminv2j1-nitilon.vercel.app/docs/transform#access-sibling-documents

**Comment by wottpal** [comment]
Hey, @sdorra, yes #290 looks pretty useful indeed. 

Though I was not able to test it, even though I've installed all the pkg.pr.new deps with `bun`. `Context.collection` still only has the `name` & `directory` attributes for me (also force-reinstalled, restarted VSCode, etc.)

**Comment by sdorra** [comment]
@wottpal you are right the github workflow has used the main branch instead of the pr head. Now the packages should contain the code from the pr. If your package manager does not refresh the packages with pr suffix (290) you could use 639c2ea as suffix e.g.:

```json
    "@content-collections/core": "https://pkg.pr.new/sdorra/content-collections/@content-collections/core@639c2ea",
    "@content-collections/mdx": "https://pkg.pr.new/sdorra/content-collections/@content-collections/mdx@639c2ea",
    "@content-collections/next": "https://pkg.pr.new/sdorra/content-collections/@content-collections/next@639c2ea",
```

**Comment by wottpal** [comment]
Works & works 👌 ✅
