### ISSUE TITLE
Export more simple `compileRawMarkdown` function

### ISSUE THREAD

**Issue by wottpal** [sdorra/content-collections#270]
I have a few cases where i need to compile markdown manually (e.g. mdx components that take markdown content as one of there parameters/attributes). Instead of installing & using a different package, I would really like to see a simple `compileRawMarkdown` (just an idea, can be named totally different) helper function to "just" compile markdown (no caching or at least optional, no page object, etc.).

At the moment, I do something like this (inspired from one of your test cases):

```ts
import type { Context, Meta } from '@content-collections/core'
import { compileMarkdown as _compileMarkdown } from '@content-collections/markdown'

type Cache = Context['cache']

const cacheNoop: Cache = async (input, fn) => {
  return fn(input)
}

const _dummyMeta: Meta = {
  directory: 'post',
  extension: '.md',
  filePath: 'post/index.md',
  fileName: 'index',
  path: '/post',
}

export const compileRawMarkdown = async (content: string) => {
  return await _compileMarkdown({ cache: cacheNoop }, { content, _meta: _dummyMeta })
}
```

**Comment by sdorra** [comment]
Okay, I understand your use case, but I'm not sure if I'm comfortable exposing such an API. The problem is that this API could not be the same as the one used for the `compile` function, due to the missing `_meta` property. That means plugins that rely on the `_meta` property will work with the `compile` function, but not with the `compileRawMarkdown` function. And without the `_meta` plugin and without the cache, what remains? Only the following few lines of code:

``´ts
const html = await unified()
  .use(remarkParse)
  .use(remarkPlugins)
  .use(remarkRehype)
  .use(rehypePlugins)
  .use(rehypeStringify)
  .process(document.content);
```

And if you don't use remark or rehype plugins you could remove the corresponding lines. I think it is fine to duplicate the code in your app.

**Comment by wottpal** [comment]
Makes sense. Never used `unified` directly before, but it works just fine and looks way simpler.
