### ISSUE TITLE
Importing react components from MDX

### ISSUE THREAD

**Issue by switz** [sdorra/content-collections#358]
Importing react components through the `mdx-components.tsx` file works just fine. But if I want to import a react component in a single mdx file, I get an error:

```
... file src/posts/driver/driver.mdx changed
build started ...
✘ [ERROR] Could not resolve "./TrafficLight"

    _mdx_bundler_entry_point-a8d6fd8e-6038-459a-9ff5-88499142313f.mdx:35:42:
      35 │ import {TrafficLight, TrafficLights} from './TrafficLight';
         ╵                                           ~~~~~~~~~~~~~~~~

... error Error: Build failed with 1 error:
_mdx_bundler_entry_point-a8d6fd8e-6038-459a-9ff5-88499142313f.mdx:35:42: ERROR: Could not resolve "./TrafficLight"
... finished build of 1 collection and 5 documents in 77ms
```

mdx file:
```mdx
---
title: Post Title
is_draft: true
---

import { TrafficLight, TrafficLights } from './TrafficLight';
```

tsconfig paths don't work either. is there a way to get imports working properly? relative or absolute?

**Comment by sdorra** [comment]
Imports are very tricky because content-collection or mdx-bundler (the library used by the @content-collections/mdx package) uses a separate build to bundle the mdx. This separate build does not know about the build process of your framework, which can cause problems. For example, importing images in Next.js is very special and will not work in this build, or next/link requires a provider, etc. But there are more problems; for example, code splitting. The separate build would bundle each used component with your mdx file and would bundle it again for each other mdx file that uses it. This is far from optimal because you will ship the same component again and again.

So enough about the problems; what about solutions?

1. You could use the components without the import and pass them to the `components` prop of `MDXContent` or `useMDXComponent`. This way, content-collections will only bundle the code of your mdx file and let the framework (Next.js, Remix, etc.) bundle the components with all the goodies like code splitting, etc.
2. Use content-collections only for the metadata and let the framework render the mdx. When you provide me with more details about your environment, I can build a sample for that.
3. You can use the `files` prop on `compileMDX` to specify your imports.

I would go with 1 or 2 because 3 is very inflexible and comes with all the described problems. I would use 3 only for things like demos, e.g., a blog that provides some samples. I use solution 3 exactly for this in my blog (https://github.com/sdorra/sdorra.dev/blob/d2b59a35dc1e62bc25e3add3096c598f9c18e58a/content-collections.ts#L54); each post can have a components folder that is bundled with the mdx file. If you have only a few imports that you want to use across your documents, 1 is a good solution, but if you have a lot of components you want to import, solution 2 is the way to go.

**Comment by switz** [comment]
I'm using next.js and rendering the mdx via the app directory:

`/[slug/page.tsx`:

```typescript
import 'server-only';

import getPosts, { getPost } from '@/lib/getPosts';
import { useMDXComponents } from '@/mdx-components';
import { MDXContent } from '@content-collections/mdx/react';
import { notFound } from 'next/navigation';

export interface PostProps {
  params: Promise<{ slug: string }>;
}

export default async function Page(props: PostProps) {
  const params = await props.params;
  const post = getPost(params.slug, 'true');

  if (!post) return notFound();

  return (
    <>
      <MDXContent code={post.mdx} components={useMDXComponents()} />
    </>
  );
}
```

I think 2 sounds like the best move, if that is feasible. I just want to make sure it all renders on the server only, and can render client components only if needed.

Thanks for your help!

**Comment by sdorra** [comment]
@switz I've created a sample that uses Content Collections to discover the MDX files but renders them with @next/mdx. 

https://www.content-collections.dev/samples/next-mdx-dynamic-import

Sadly, this method does not currently work with Turborepo. I think we need a custom loader to get Turborepo to work. When I have more time, I will have a look at this.

**Comment by switz** [comment]
Thank you so much! This works great, but two questions:

1. I followed the instructions, but my frontmatter is not being removed. I added the appropriate plugins to next.config
2. My slug is not always the same as the fileName – could we expose the file name and/or path to the `doc`?

I really appreciate the help here. Thanks again.

**Comment by sdorra** [comment]
Each document has a `_meta property` (unless it has been removed in the transform function) that contains metadata about the document, such as the file path and the file name. To access the path of your document, you can use `doc._meta.path`.

**Comment by switz** [comment]
Thanks for your patience with my ignorance. I see it now.

This is a great solve. Thank you.
