### ISSUE TITLE
Support output files split

### ISSUE THREAD

**Issue by acomanescu** [sdorra/content-collections#430]
Is it possible to split the files instead of having a single js file with all the posts?

**Comment by sdorra** [comment]
This is not possible at the moment. Can you describe your environment and why you want to split the output?

**Comment by sdorra** [comment]
I understand. We could add a function to export fields, such as content, into a separate file for import.

The next version of content collections already has a similar concept for static imports, which could solve your problem. 

You could use the [next/mdx](https://nextjs.org/docs/pages/building-your-application/configuring/mdx) package to compile your MDX instead of using `@content-collections/mdx`, and utilize content collections to gather the files and their metadata. Content collections could create a static import for the MDX content. This way, you would have one file for each piece of content and one file for the metadata of all files.

If you think this could work for you, I can create a sample in the next few days.

**Comment by sdorra** [comment]
@acomanescu i've finished the sample:

https://github.com/sdorra/content-collections/tree/main/samples/next-mdx-static-import

> Do you have any estimate for the next version release?

I can't say yet. There is one more feature planned, the documentation is not yet ready, and there is a turbopack problem.

**Comment by sdorra** [comment]
@acomanescu i still fighting against the turbo repo bug, so the version which includes `createDefaultImport` is not yet released. But you can use a pre release if you want:

https://github.com/sdorra/content-collections/runs/34392860978

For example:

```json
{
  "dependencies": {
    "@content-collections/core": "https://pkg.pr.new/sdorra/content-collections/@content-collections/core@0d4405d",
    "@content-collections/next": "https://pkg.pr.new/sdorra/content-collections/@content-collections/next@0d4405d"
  }
}
```

**Comment by wottpal** [comment]
> [@acomanescu](https://github.com/acomanescu) i've finished the sample:
> 
> https://github.com/sdorra/content-collections/tree/main/samples/next-mdx-static-import
> 
> > Do you have any estimate for the next version release?
> 
> I can't say yet. There is one more feature planned, the documentation is not yet ready, and there is a turbopack problem.

@sdorra Is this still the way to go for static imports?

**Comment by sdorra** [comment]
@wottpal yes, the [next-mdx-static-import](https://www.content-collections.dev/samples/next-mdx-dynamic-import) is up to date and shows the way to go for static imports.

**Comment by erikdemarco** [comment]
What about vite?
